/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/Metadannye-DBW) сборочных заданий  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/knowledge-base/articles/019d49a4-036a-7721-98e8-bed5f1a4f72d/zakazy-dbw\">инструкции</a> по работе с <strong>заказами DBW</strong> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiOrdersMetaDleteRequestV2
 */
export interface ApiOrdersMetaDleteRequestV2 {
    /**
     * Название метаданных для удаления (imei, uin, gtin, sgtin). Передаётся только одно значение
     * @type {string}
     * @memberof ApiOrdersMetaDleteRequestV2
     */
    key?: string;
    /**
     * Список ID сборочных заданий
     * @type {Array<number>}
     * @memberof ApiOrdersMetaDleteRequestV2
     */
    ordersIds?: Array<number>;
}

/**
 * Check if a given object implements the ApiOrdersMetaDleteRequestV2 interface.
 */
export function instanceOfApiOrdersMetaDleteRequestV2(value: object): value is ApiOrdersMetaDleteRequestV2 {
    return true;
}

export function ApiOrdersMetaDleteRequestV2FromJSON(json: any): ApiOrdersMetaDleteRequestV2 {
    return ApiOrdersMetaDleteRequestV2FromJSONTyped(json, false);
}

export function ApiOrdersMetaDleteRequestV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiOrdersMetaDleteRequestV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'ordersIds': json['ordersIds'] == null ? undefined : json['ordersIds'],
    };
}

export function ApiOrdersMetaDleteRequestV2ToJSON(json: any): ApiOrdersMetaDleteRequestV2 {
    return ApiOrdersMetaDleteRequestV2ToJSONTyped(json, false);
}

export function ApiOrdersMetaDleteRequestV2ToJSONTyped(value?: ApiOrdersMetaDleteRequestV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'ordersIds': value['ordersIds'],
    };
}

